In [10]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [2]:
dftest = pd.read_csv("testo.csv")
dftrain = pd.read_csv("traino.csv")

In [3]:
dftest.head()

id  Gender        Age    Height      Weight  \
0  20758    Male  26.899886  1.848294  120.644178   
1  20759  Female  21.000000  1.600000   66.000000   
2  20760  Female  26.000000  1.643355  111.600553   
3  20761    Male  20.979254  1.553127  103.669116   
4  20762  Female  26.000000  1.627396  104.835346   

  family_history_with_overweight FAVC      FCVC       NCP       CAEC SMOKE  \
0                            yes  yes  2.938616  3.000000  Sometimes    no   
1                            yes  yes  2.000000  1.000000  Sometimes    no   
2                            yes  yes  3.000000  3.000000  Sometimes    no   
3                            yes  yes  2.000000  2.977909  Sometimes    no   
4                            yes  yes  3.000000  3.000000  Sometimes    no   

       CH2O SCC       FAF       TUE       CALC                 MTRANS  
0  2.825629  no  0.855400  0.000000  Sometimes  Public_Transportation  
1  3.000000  no  1.000000  0.000000  Sometimes  Public_Transportation  
2  2.621877  no  0.000000  0.250502  Sometimes  Public_Transportation  
3  2.786417  no  0.094851  0.000000  Sometimes  Public_Transportation  
4  2.653531  no  0.000000  0.741069  Sometimes  Public_Transportation

In [4]:
dftrain.head()

id  Gender        Age    Height      Weight family_history_with_overweight  \
0   0    Male  24.443011  1.699998   81.669950                            yes   
1   1  Female  18.000000  1.560000   57.000000                            yes   
2   2  Female  18.000000  1.711460   50.165754                            yes   
3   3  Female  20.952737  1.710730  131.274851                            yes   
4   4    Male  31.641081  1.914186   93.798055                            yes   

  FAVC      FCVC       NCP        CAEC SMOKE      CH2O SCC       FAF  \
0  yes  2.000000  2.983297   Sometimes    no  2.763573  no  0.000000   
1  yes  2.000000  3.000000  Frequently    no  2.000000  no  1.000000   
2  yes  1.880534  1.411685   Sometimes    no  1.910378  no  0.866045   
3  yes  3.000000  3.000000   Sometimes    no  1.674061  no  1.467863   
4  yes  2.679664  1.971472   Sometimes    no  1.979848  no  1.967973   

        TUE       CALC                 MTRANS           NObeyesdad  
0  0.976473  Sometimes  Public_Transportation  Overweight_Level_II  
1  1.000000         no             Automobile        Normal_Weight  
2  1.673584         no  Public_Transportation  Insufficient_Weight  
3  0.780199  Sometimes  Public_Transportation     Obesity_Type_III  
4  0.931721  Sometimes  Public_Transportation  Overweight_Level_II

In [5]:
dftest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13840 entries, 0 to 13839
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              13840 non-null  int64  
 1   Gender                          13840 non-null  object 
 2   Age                             13840 non-null  float64
 3   Height                          13840 non-null  float64
 4   Weight                          13840 non-null  float64
 5   family_history_with_overweight  13840 non-null  object 
 6   FAVC                            13840 non-null  object 
 7   FCVC                            13840 non-null  float64
 8   NCP                             13840 non-null  float64
 9   CAEC                            13840 non-null  object 
 10  SMOKE                           13840 non-null  object 
 11  CH2O                            13840 non-null  float64
 12  SCC                             

In [6]:
dftrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              20758 non-null  int64  
 1   Gender                          20758 non-null  object 
 2   Age                             20758 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  object 
 6   FAVC                            20758 non-null  object 
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  object 
 10  SMOKE                           20758 non-null  object 
 11  CH2O                            20758 non-null  float64
 12  SCC                             

In [7]:
dftrain.describe()

id           Age        Height        Weight          FCVC  \
count  20758.00000  20758.000000  20758.000000  20758.000000  20758.000000   
mean   10378.50000     23.841804      1.700245     87.887768      2.445908   
std     5992.46278      5.688072      0.087312     26.379443      0.533218   
min        0.00000     14.000000      1.450000     39.000000      1.000000   
25%     5189.25000     20.000000      1.631856     66.000000      2.000000   
50%    10378.50000     22.815416      1.700000     84.064875      2.393837   
75%    15567.75000     26.000000      1.762887    111.600553      3.000000   
max    20757.00000     61.000000      1.975663    165.057269      3.000000   

                NCP          CH2O           FAF           TUE  
count  20758.000000  20758.000000  20758.000000  20758.000000  
mean       2.761332      2.029418      0.981747      0.616756  
std        0.705375      0.608467      0.838302      0.602113  
min        1.000000      1.000000      0.000000      0.000000  
25%        3.000000      1.792022      0.008013      0.000000  
50%        3.000000      2.000000      1.000000      0.573887  
75%        3.000000      2.549617      1.587406      1.000000  
max        4.000000      3.000000      3.000000      2.000000

In [9]:
dftrain.corr()

/var/folders/4l/srn7gtws4zsbq_ndc7mwjs880000gn/T/ipykernel_31363/533448645.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  dftrain.corr()


id       Age    Height    Weight      FCVC       NCP      CH2O  \
id      1.000000  0.007634  0.012041  0.014020  0.002098 -0.000332  0.007917   
Age     0.007634  1.000000 -0.011713  0.283381  0.034414 -0.048479 -0.016325   
Height  0.012041 -0.011713  1.000000  0.416677 -0.071546  0.191383  0.183706   
Weight  0.014020  0.283381  0.416677  1.000000  0.245682  0.095947  0.317914   
FCVC    0.002098  0.034414 -0.071546  0.245682  1.000000  0.113349  0.101299   
NCP    -0.000332 -0.048479  0.191383  0.095947  0.113349  1.000000  0.080949   
CH2O    0.007917 -0.016325  0.183706  0.317914  0.101299  0.080949  1.000000   
FAF     0.016719 -0.192259  0.295278 -0.084845 -0.089822  0.100871  0.082932   
TUE     0.007667 -0.296154  0.076433 -0.086471 -0.147843  0.067459 -0.010654   

             FAF       TUE  
id      0.016719  0.007667  
Age    -0.192259 -0.296154  
Height  0.295278  0.076433  
Weight -0.084845 -0.086471  
FCVC   -0.089822 -0.147843  
NCP     0.100871  0.067459  
CH2O    0.082932 -0.010654  
FAF     1.000000  0.021213  
TUE     0.021213  1.000000

In [17]:
le = preprocessing.LabelEncoder()
cols = ['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE', 'SCC', 'CALC', 'MTRANS']

for col in cols:
    dftrain[col] = le.fit_transform(dftrain[col])
    dftest[col] = le.fit_transform(dftest[col])
    print(le.classes_)

dftrain.head()

[0 1]
[0 1]
[0 1]
[0 1 2 3]
[0 1]
[0 1]
[0 1 2 3]
[0 1 2 3 4]


id  Gender        Age    Height      Weight  \
0   0       1  24.443011  1.699998   81.669950   
1   1       0  18.000000  1.560000   57.000000   
2   2       0  18.000000  1.711460   50.165754   
3   3       0  20.952737  1.710730  131.274851   
4   4       1  31.641081  1.914186   93.798055   

   family_history_with_overweight  FAVC      FCVC       NCP  CAEC  SMOKE  \
0                               1     1  2.000000  2.983297     2      0   
1                               1     1  2.000000  3.000000     1      0   
2                               1     1  1.880534  1.411685     2      0   
3                               1     1  3.000000  3.000000     2      0   
4                               1     1  2.679664  1.971472     2      0   

       CH2O  SCC       FAF       TUE  CALC  MTRANS  NObeyesdad  
0  2.763573    0  0.000000  0.976473     1       3           6  
1  2.000000    0  1.000000  1.000000     2       0           1  
2  1.910378    0  0.866045  1.673584     2       3           0  
3  1.674061    0  1.467863  0.780199     1       3           4  
4  1.979848    0  1.967973  0.931721     1       3           6

In [18]:
dftrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              20758 non-null  int64  
 1   Gender                          20758 non-null  int64  
 2   Age                             20758 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  int64  
 6   FAVC                            20758 non-null  int64  
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  int64  
 10  SMOKE                           20758 non-null  int64  
 11  CH2O                            20758 non-null  float64
 12  SCC                             

In [19]:
dftrain.corr()

id    Gender       Age    Height  \
id                              1.000000 -0.000923  0.007634  0.012041   
Gender                         -0.000923  1.000000  0.066530  0.623507   
Age                             0.007634  0.066530  1.000000 -0.011713   
Height                          0.012041  0.623507 -0.011713  1.000000   
Weight                          0.014020  0.118613  0.283381  0.416677   
family_history_with_overweight  0.010482  0.095786  0.261575  0.228137   
FAVC                            0.004156  0.021812  0.056848  0.115566   
FCVC                            0.002098 -0.312766  0.034414 -0.071546   
NCP                            -0.000332  0.039468 -0.048479  0.191383   
CAEC                            0.001904  0.046129  0.151498  0.069003   
SMOKE                           0.011544  0.063349  0.056006  0.069748   
CH2O                            0.007917  0.053298 -0.016325  0.183706   
SCC                            -0.011162 -0.061442 -0.108855 -0.095923   
FAF                             0.016719  0.238399 -0.192259  0.295278   
TUE                             0.007667  0.058696 -0.296154  0.076433   
CALC                            0.006406  0.037345 -0.070323 -0.089138   
MTRANS                          0.013372 -0.140049 -0.605345 -0.049543   
NObeyesdad                      0.012329  0.046575  0.283018  0.060786   

                                  Weight  family_history_with_overweight  \
id                              0.014020                        0.010482   
Gender                          0.118613                        0.095786   
Age                             0.283381                        0.261575   
Height                          0.416677                        0.228137   
Weight                          1.000000                        0.514147   
family_history_with_overweight  0.514147                        1.000000   
FAVC                            0.228770                        0.152154   
FCVC                            0.245682                        0.047756   
NCP                             0.095947                        0.044778   
CAEC                            0.337331                        0.204263   
SMOKE                           0.040416                        0.018782   
CH2O                            0.317914                        0.191588   
SCC                            -0.185116                       -0.166760   
FAF                            -0.084845                       -0.094414   
TUE                            -0.086471                        0.005762   
CALC                           -0.216673                        0.002330   
MTRANS                         -0.008431                       -0.109662   
NObeyesdad                      0.431821                        0.321325   

                                    FAVC      FCVC       NCP      CAEC  \
id                              0.004156  0.002098 -0.000332  0.001904   
Gender                          0.021812 -0.312766  0.039468  0.046129   
Age                             0.056848  0.034414 -0.048479  0.151498   
Height                          0.115566 -0.071546  0.191383  0.069003   
Weight                          0.228770  0.245682  0.095947  0.337331   
family_history_with_overweight  0.152154  0.047756  0.044778  0.204263   
FAVC                            1.000000  0.006952  0.011522  0.115675   
FCVC                            0.006952  1.000000  0.113349 -0.010870   
NCP                             0.011522  0.113349  1.000000 -0.089957   
CAEC                            0.115675 -0.010870 -0.089957  1.000000   
SMOKE                          -0.016009 -0.012191  0.006820 -0.019703   
CH2O                            0.039167  0.101299  0.080949  0.132820   
SCC                            -0.111897  0.022120  0.006633 -0.099427   
FAF                            -0.067030 -0.089822  0.100871 -0.092035   
TUE                             0.034843 -0.147843  0.067459 -0.049646   
CA

In [22]:
sns.pairplot(data=dftrain)